title = "HZ's Personal Website"
languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "HZ"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Moments."

  [params.homepage]
    showRecentItems = 5
    description = """
    Welcome to my personal corner. Here I share my thoughts on research, experiments in the kitchen, and moments captured through my lens.
    """

  [params.author]
    name = "HZ"
    headline = "Student"
    bio = "A student."
    
    # Make sure static/images/me.jpg exists
    # image = "me.jpg" 
    # imageQuality = 96

    # links = [
    #   { email = "mailto:a@gmail.edu" },
      { link = "https://professional.z-hg.com", icon = "briefcase", text = "Professional Page" },
    #   { github = "https://github.com/a" }
    # ]