title = "HZ's Professional Website"
languageCode = "en"
languageName = "English"
weight = 1

[params]
  displayName = "HZ"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Moments."

  [params.homepage]
    showRecentItems = 5
    description = """
    Welcome to my professional corner.
    """

  [params.author]
    name = "HZ"
    headline = "Student"
    bio = "A student."
    
    # Make sure static/images/me.jpg exists
    # image = "me.jpg" 
    # imageQuality = 96

    links = [
      { link = "https://personal.z-hg.com", icon = "briefcase", text = "Personal Page" }
    ]